# Generated by Django 4.0.6 on 2022-07-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique number')),
                ('city', models.CharField(max_length=500, verbose_name='City for search weather')),
                ('result', models.CharField(max_length=500, verbose_name='result of job')),
                ('date', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='date of request')),
            ],
        ),
    ]
